export const SET_PRODUCTS_CATEGORIES = 'SET_PRODUCTS_CATEGORIES';
export const GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS;';
export const GET_SINGLE_PRODUCT = 'GET_SINGLE_PRODUCT';
export const GET_PRODUCTS_BY_CATEGORY = 'GET_PRODUCTS_BY_CATEGORY';
export const GET_TRENDING_PRODUCTS = 'GET_TRENDING_PRODUCTS';
export const SEARCH_PRODUCTS = 'SEARCH_PRODUCTS';

export const SET_SINGLE_PRODUCT = 'SET_SINGLE_PRODUCT';

export type ActionTypes =
  | typeof SET_PRODUCTS_CATEGORIES
  | typeof GET_PRODUCTS_SUCCESS
  | typeof GET_PRODUCTS_FAILURE
  | typeof GET_TRENDING_PRODUCTS
  | typeof GET_SINGLE_PRODUCT
  | typeof GET_PRODUCTS_BY_CATEGORY
  | typeof SEARCH_PRODUCTS
  | typeof SET_SINGLE_PRODUCT;
